### ISSUE TITLE
undefined method to_h for Array

### ISSUE THREAD

**Issue by salf** [gregnavis/active_record_doctor#1]
Just tried on current project (ruby 2.0.0p598 / rails 4.2.5.1):
➜ ✗ rake active_record_doctor:unindexed_foreign_keys > unindexed_foreign_keys.txt

> rake aborted!
> NoMethodError: undefined method to_h for #<Array:0x007faf6c25abc0>
> /Users/salf/.rvm/gems/ruby-2.0.0-p598/gems/active_record_doctor-1.0.2/lib/active_record_doctor/tasks/unindexed_foreign_keys.rb:32:in `unindexed_foreign_keys'

**Comment by gregnavis** [comment]
Hey @salf! Thanks for the report. I'll take a look at the issue on Wednesday.

**Comment by gregnavis** [comment]
@salf I fixed it and release version 1.1.1. Please update the gem and try again. If you can spot any other issues just open an issue. I'm glad to help.
