### ISSUE TITLE
Errors generate

### ISSUE THREAD

**Issue by BorisBresciani** [gregnavis/active_record_doctor#11]
Hey

I have this error:
`/home/XXXX/.rvm/gems/ruby-2.3.3/gems/active_record_doctor-1.3.0/lib/generators/active_record_doctor/add_indexes/add_indexes_generator.rb:30:in `content': undefined method `camelize' for nil:NilClass (NoMethodError)
`

When I execute the command:
`rails generate active_record_doctor:add_indexes unindexed_foreign_keys.txt`

Thanks !

**Comment by gregnavis** [comment]
Could you post `unindexed_foreign_keys.txt` here?

**Comment by gregnavis** [comment]
@BorisBresciani it seems the issue here is that a line in `unindexed_foreign_keys.txt` starts with a space. I'll improve the tool to make it behave better in such cases. For now, please ensure that no line is prefixed by a space.

**Comment by gregnavis** [comment]
Addressed in d20798ec1c526b445f519df1b54b37d368997b0a.
