### ISSUE TITLE
Consider adding check for `change_column_default(..., to: nil)`

### ISSUE THREAD

**Issue by cscorley** [gregnavis/active_record_doctor#141]
Hi friends,

Thank you for this project, it has been incredibly useful for me.

Earlier today we had an incident that I think could be a good Doctor candidate.

Context:  We use Doorkeeper to issue OAuth2 tokens.  We set this up initially to only issue tokens to Users, but have recently found the need to have more than one resource owner type. So, we went to enable the Doorkeeper option `use_polymorphic_resource_owner` which would allow this use case.  By default, with this option off, Doorkeeper only creates tables that have a column `resource_owner_id` and no `resource_owner_type`.  We are using Rails 6.1.7.3 and Doorkeeper 5.6.6.  We run database migrations before we start our deployment rollouts.

To achieve this, our strategy was over three deploys:

1. Create a migration which added `resource_owner_type` with default value as `"User"`.  Below is the migration, and it is pretty close to the Doorkeeper generated one with exception to the default value.  We chose to use a default value on column creation due to the scale of our tables.
```ruby
class EnablePolymorphicResourceOwner < ActiveRecord::Migration[6.1]
  def change
    add_column :oauth_access_tokens, :resource_owner_type, :string, default: 'User'
    add_column :oauth_access_grants, :resource_owner_type, :string, null: false, default: 'User'

    add_index :oauth_access_tokens,
              [:resource_owner_id, :resource_owner_type],
              name: 'polymorphic_owner_oauth_access_tokens'

    add_index :oauth_access_grants,
              [:resource_owner_id, :resource_owner_type],
              name: 'polymorphic_owner_oauth_access_grants'
  end
end
```
2. Turn on `use_polymorphic_resource_owner` in the Doorkeeper init
3. Remove the default value for `resource_owner_type`
```ruby
class RemoveDoorkeeperDefaultColumns < ActiveRecord::Migration[6.1]
  def change
    change_column_default(:oauth_access_tokens, :resource_owner_type, from: "User", to: nil)
    change_column_default(:oauth_access_grants, :resource_owner_type, from: "User", to: nil)
  end
end
```

The migration itself when OK, but the "gotcha" we ran into when deploying step 3 is that during the rollout, there were still Rails instances on step 2 after the database migration for step 3 had already ran.  These Rails instances still had a schema.rb + cache that thought the column had a default of "User" -- while the database no longer had the default.  ActiveRecord in this case does not send values for those columns for newly created objects when the values match the default (by my testing on 6.1.7.3), even if the objects are instantiated with explicit values.

Thanks!

**Comment by fatkodima** [comment]
This gem does not inspect migrations. From my understanding of your problem, you should use another gem, specifically designed to inspect migrations, like https://github.com/fatkodima/online_migrations, if you are on postgres.

**Comment by cscorley** [comment]
Oops! Sorry. In my rush to get an issue opened somewhere I went to the wrong gem! Long day 😅

**Comment by fatkodima** [comment]
> Thank you for this project, it has been incredibly useful for me.

But I hope, that it does not cancel these words 😅

**Comment by cscorley** [comment]
Absolutely does not! Thanks again for this project. I rely on it to help me realize better choices all the time 😆
