### ISSUE TITLE
Will not run when RAILS_ENV=test

### ISSUE THREAD

**Issue by dogweather** [gregnavis/active_record_doctor#147]
Hi,

I'm trying to use A_R_D in CI, with a test database, and the test environment. It works fine when in development mode.

But this fails with `Don't know how to build task 'active_record_doctor'`:

**Gemfile**

```ruby
group :development, :test do
  gem 'active_record_doctor'
end
```

**Command Line**

```
env RAILS_ENV=test rake active_record_doctor

Don't know how to build task 'active_record_doctor'...
```

I've tried a few variations of setting the Rails env. There seems to be something weird going on when `RAILS_ENV` is set to `test`.

**Comment by fatkodima** [comment]
Can not reproduce. Can you reproduce with the latest changes from `master`? If so, it would be helpful if you provide us a sample rails app that demonstrates an issue.

**Comment by dogweather** [comment]
Thank you! I'll look into it. Please assume it's user error for now. I appreciate your time.

**Comment by dogweather** [comment]
Yes! Thank you.
