### ISSUE TITLE
Rails 5.2 support

### ISSUE THREAD

**Issue by cpgo** [gregnavis/active_record_doctor#15]
Any plans to update the gemfiles to Rails 5.2?

**Comment by gregnavis** [comment]
Definitely yes! Thank you for reminding me.

**Comment by gregnavis** [comment]
@cpgo could you clarify what's the issue? I just installed in a Rails 5.2 project without any issues.

**Comment by cpgo** [comment]
I had no issues updating to rails 5.2, I just noticed that there wasnt a rails5.2 gemfile [here](https://github.com/gregnavis/active_record_doctor/tree/master/gemfiles).
But it seems to be there now 😄

**Comment by gregnavis** [comment]
These gem files are only used for testing purposes - see [`.travis.yml`](https://github.com/gregnavis/active_record_doctor/blob/098880e5f2ecfcfa2a0c8f9d1e41fe35121e77e7/.travis.yml) for more information.

I'm closing the issue. If you run into any problems with Rails 5.2 feel free to reopen or submit another issue.
