### ISSUE TITLE
MissingPresenceValidation should ignore enum's with default values

### ISSUE THREAD

**Issue by fidalgo** [gregnavis/active_record_doctor#154]
If you have a model, where an enum is defined with a `default` (or `_default`_ keyword) like this:
```
class Profile < ApplicationRecord
    enum kind: {general: 0, admin: 1}, _default: :general
end

The report should not include a missing presence validator for the field.

**Comment by gregnavis** [comment]
This doesn't sound like a bug as a default value doesn't prevent the color from creating a model with an explicit nil value. For example:

```ruby
Profile.create!(kind: nil)
```

I think in this case `active_record_doctor` discovered an actual bug or edge case in your code. I recommend that you ignore that warning via configuration or add a strict validator.
