### ISSUE TITLE
Running the undefined_table_references task loads Rails twice

### ISSUE THREAD

**Issue by CodingAnarchy** [gregnavis/active_record_doctor#16]
```
.../lib/group_state_manager.rb:32: warning: already initialized constant GroupStateManager::LOGGING_ENABLED
.../lib/group_state_manager.rb:32: warning: previous definition of LOGGING_ENABLED was here
```

I get duplicate initialization of files in my `lib/` directory when running the `undefined_table_references` task (and only that one).  See above for an example sanitized snippet.

**Comment by gregnavis** [comment]
It seems it's the only task (except the unreleased `missing_unique_indexes`) that use `Rails.application.eager_load!`. If you add a rake task to `lib/tasks/test.rake` like:

```ruby
task :eager_load_test => :environment do
  Rails.application.eager_load!
end
```

and run `bundle exec rake eager_load_test` then does that cause the double-loading?

It seems I can't reproduce that in any repos I have here but it might be related to app configuration.

**Comment by gregnavis** [comment]
@CodingAnarchy I haven't heard back from you and no one else is reporting problems like that so I'm going to close this for now. Feel free to reopen if that's still a problem.
