### ISSUE TITLE
Detect tables without a primary key

### ISSUE THREAD

**Issue by fatkodima** [gregnavis/active_record_doctor#172]
There is no good reason to not to have a primary key on the table. But I saw this before.
This can lead to troubles like being able to easily find a specific record, logical replication in PostgreSQL will be troublesome, because all the rows need to be unique in the table then, etc.

**Comment by hlascelles** [comment]
We'd love this too. In fact we added this test just last week:

```ruby
  it "checks all tables have a primary key (needed for Blue / Green logical replication)" do
    no_pk_tables = ActiveRecord::Base.connection.execute(<<~SQL).to_a
      SELECT pgc.relname as "table", pgns.nspname as "namespace"
      FROM pg_class pgc 
      JOIN pg_namespace pgns ON pgns.oid = pgc.relnamespace 
      WHERE pgc.relkind = 'r'
      AND pgns.nspname NOT IN ('pg_catalog', 'information_schema')
      AND pgc.oid NOT IN
        (
          SELECT pgc.oid
          FROM pg_class pgc 
          JOIN pg_index pgi ON pgi.indrelid = pgc.oid 
          JOIN pg_namespace pgns ON pgns.oid = pgc.relnamespace
          WHERE pgi.indisprimary = true
          AND pgc.relkind = 'r'
        );
    SQL

    expect(no_pk_tables).to be_empty, "Tables with no primary key: #{no_pk_tables}"
  end
```

... Then realised it could/should be in ARD. So here we are.

**Comment by gregnavis** [comment]
@fatkodima, thanks for the suggestion! @hlascelles, thank you for sharing that.

I think it would be a good addition.

**Comment by fatkodima** [comment]
@gregnavis Do you want to implement it by yourself or should I?
