### ISSUE TITLE
missing_not_null_constraint error when validating presence only on create

### ISSUE THREAD

**Issue by ali-hiringthing** [gregnavis/active_record_doctor#188]
Hello,

We have a use case where we need a record to be created with required fields, but these fields aren't required on updates.

Our validation setup looks like this:
`validates :city, presence: true, on: :create`

This column can still end up being null if the user deletes the value after it's initial creation. This leads to a missing_not_null_constraint error.

 Was this behavior intentional or is this a bug?

Thanks

**Comment by fatkodima** [comment]
Yes, these should be ignored.
