### ISSUE TITLE
feature request: missing_presence_validation set flag to ignore if default set

### ISSUE THREAD

**Issue by baronworks** [gregnavis/active_record_doctor#20]
Been using active_record_doctor:missing_presence_validation and find that over 75% of the columns listed have defaults defined in the db and in this case no active record validation is needed for these.

For me having a way to ignore any columns with defaults set would be a nice feature and filter out a lot of work not needed.

Great Gem and Thanks

**Comment by gregnavis** [comment]
Thank for your kind words. I'm glad you find the gem useful.

This would definitely be a great feature to have. I'll add it to the roadmap.

**Comment by gregnavis** [comment]
@baronworks, I'm working on a new release and wanted to include your request. However, I realized that a default does **NOT** mean a validation is not required. If you explicitly pass `nil` for a column value then the default would be ignored.

**Comment by gregnavis** [comment]
I'm closing this as my current understanding is columns with defaults may still require validation. @baronworks, feel free to add more details to the discussion if I misunderstood your case.
