### ISSUE TITLE
Allow models backed by a DB view in undefined_table_references

### ISSUE THREAD

**Issue by foca** [gregnavis/active_record_doctor#26]
We've introduced models backed by database views to improve some associations, and now the doctor is complaining that the model doesn't have a valid table.

Which fair point: it doesn't. But the model is valid and works well in production, so we've had to remove this task from our CI process as it was preventing the build from being successful.

`undefined_table_references` should both get the list of tables _and_ views in the database, since ActiveRecord works well with views to back a (read only) model.

**Comment by gregnavis** [comment]
@foca thanks for opening the issue. Which Rails version are you using? I'm guessing 4.2 as it should work on higher versions.

I already implemented support for this for Rails 4.2 + PostgreSQL and will release soon. Stay tuned!

**Comment by foca** [comment]
Yes, sorry, 4.2.

Thank you so much ❤️

**Comment by gregnavis** [comment]
Fixes in 1.7.0.
