### ISSUE TITLE
polymorphic associations bug

### ISSUE THREAD

**Issue by kvokka** [gregnavis/active_record_doctor#3]
My model
```
# Table name: configs
#
#  configurable_id   :integer
#  configurable_type :string
#
# Indexes
#
#  index_configs_on_configurable_type_and_configurable_id  (configurable_type,configurable_id)
```

but tool do not see this association and try to add index to `configurable_id`

**Comment by gregnavis** [comment]
Thanks for reporting. I'll fix this in the next release.

**Comment by michaelachrisco** [comment]
Well shoot, came across this one as well. Looking forward to the next release.
