### ISSUE TITLE
Display list of tasks at top of readme

### ISSUE THREAD

**Issue by jaredmoody** [gregnavis/active_record_doctor#36]
Scrolling through the README to find the name of the task I want to run is a little cumbersome. What do you think about listing them at the top of the file with links to the full descriptions?

**Comment by jaredmoody** [comment]
Also if #18 were resolved, that would help this a bit - right now scrolling through the readme or reading the code are the only ways of getting the task names. 

I'll take a look at #18 and see what I can do.

**Comment by gregnavis** [comment]
Both this and #18 are now fixed on `master`. Thank you for reporting the issue!
