### ISSUE TITLE
Suggestion: Check for IDs using Integers instead of BigInt

### ISSUE THREAD

**Issue by fidalgo** [gregnavis/active_record_doctor#38]
Given no one is immune to it https://m.signalvnoise.com/update-on-basecamp-3-being-stuck-in-read-only-as-of-nov-8-922am-cst/

and there's a lot of people using Rails from prior this https://github.com/rails/rails/pull/26266

So a check for it would be awesome!

**Comment by gregnavis** [comment]
Absolutely love the suggestion, @fidalgo! I'll add a check.

**Comment by fidalgo** [comment]
@gregnavis by ID's I mean ID's and foreign keys, because if you have one as Integer and another as BitInt... :boom:
