### ISSUE TITLE
undefined_table_references - uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQLAdapter

### ISSUE THREAD

**Issue by dougc84** [gregnavis/active_record_doctor#54]
When running `bundle exec rake active_record_doctor:undefined_table_references` on an app (Rails 6, FWIW) with MySQL, it throws a `NameError: uninitialized constant ActiveRecord::ConnectionAdapters::PostgreSQLAdapter` exception.  Obviously, there's a DB type check missing somewhere.  All others are functional.  This isn't something I'm worried about at the moment or I'd try to form a PR, but just passing it on.

**Comment by gregnavis** [comment]
@dougc84, do you have a backtrace handy? My guess is it's coming from [`Base#views`](https://github.com/gregnavis/active_record_doctor/blob/master/lib/active_record_doctor/tasks/base.rb#L47) as it's the only place where that adapter is being referenced explicitly.

**Comment by dougc84** [comment]
> @dougc84, do you have a backtrace handy? My guess is it's coming from [`Base#views`](https://github.com/gregnavis/active_record_doctor/blob/master/lib/active_record_doctor/tasks/base.rb#L47) as it's the only place where that adapter is being referenced explicitly.

I submitted this issue over a month ago.  I've long since moved on.

**Comment by gregnavis** [comment]
Fixed in 1.8.0.
