### ISSUE TITLE
Cannot load such file -- active_record_doctor/tasks/extraneous_indexes after upgrading from 1.7.1 => 1.8.0 

### ISSUE THREAD

**Issue by owst** [gregnavis/active_record_doctor#64]
Hi, thanks for the gem, we find it very useful!

Just to let you know that a minor-version upgrade from 1.7.1 => 1.8.0 is not backwards compatible, with errors such as
`cannot load such file -- active_record_doctor/tasks/extraneous_indexes`

As I couldn't see anything mentioning this in the changelog, I had a dig and it looks like this came from https://github.com/gregnavis/active_record_doctor/commit/b19209060bcd9dccc2578a2d2dcf62b753287e63 -
if this project aims to use semantic versioning, then this change should have been part of a major version change.

For the record, the fix was easy, we just renamed `/tasks/` to `/detectors/` in our require paths for `active_record_doctor` and the corresponding module name (`ActiveRecordDoctor::Tasks` => `ActiveRecordDoctor::Detectors`) where we explicitly referred to one.

**Comment by gregnavis** [comment]
Thanks for reporting the issue.

Active Record Doctor is meant to be used via the rake task only. By requiring those files you rely on implementation details. I assume you do that from your test suite so that active_record_doctor can be used as part of your build, is that correct? I'd like to understand your use case better to ensure it's covered by future releases.

**Comment by owst** [comment]
hi @gregnavis

Yes, we use ARD in our test suite, currently we run `ActiveRecordDoctor::Detectors::ExtraneousIndexes`, `ActiveRecordDoctor::Detectors::UnindexedForeignKeys` and `ActiveRecordDoctor::Detectors::MissingForeignKeys` directly as `clazz.new.run`. In all three cases we post-process the output and remove certain known false positives, and thus have tests that say something like `expect(remove_known_false_positives(output)).to be_empty`.

It looks like the functionality we're missing (either because it's not there, or we haven't found it!) is:
1. The ability to ignore certain indices (for `ExtraneousIndexes`)
2. The ability to ignore certain columns for `UnindexedForeignKeys` and `MissingForeignKeys` (e.g. a column named "_id" that isn't used as a foreign key, despite the name suggesting it would be)
3. The ability to ignore (materialised) views, as it looks like they trip up `UnindexedForeignKeys` and `MissingForeignKeys`, despite the underlying tables having the required index/FK

Hope that helps!

**Comment by fatkodima** [comment]
@owst 
Can you a bit explain this? Do you have any views/materialized views and this check suggests indexes on them?
> The ability to ignore (materialised) views, as it looks like they trip up UnindexedForeignKeys and MissingForeignKeys, despite the underlying tables having the required index/FK

Seems like this cannot happen, because this check runs only on database tables
https://github.com/gregnavis/active_record_doctor/blob/048999f6141325cac03f8f517a2a161a298c2e3d/lib/active_record_doctor/detectors/unindexed_foreign_keys.rb#L12

**Comment by owst** [comment]
Hi @fatkodima,

I might have confused things here. It seems that v1.7.2 (with Rails 5, that we are using) _did_ include views as well as tables: https://github.com/gregnavis/active_record_doctor/blob/72b91d15a3857885db32e6e4142c3744cfc1e805/lib/active_record_doctor/tasks/base.rb#L32-L39

but in 1.8.0, only tables are considered.

**Comment by gregnavis** [comment]
@owst, I've just released v1.9.0.rc1 which should address some of your issues. Please add the following to `Gemfile`:

```ruby
gem "active_record_doctor", "= 1.9.0.rc1"
```

and run `bundle install`. Detailed installation and usage instructions are in the README. If you stumble upon any issues then please report them here.

**Comment by gregnavis** [comment]
@owst, I'm closing the issue as it's addressed in 1.9.0 which I released a few minutes ago. Please consult the updated README for instructions on how to configure the tool to ignore certain warnings.

**Comment by owst** [comment]
Sorry for the slow reply @gregnavis - the changes in v1.9 look great, thanks!
