### ISSUE TITLE
Check for has_one backed by a unique index

### ISSUE THREAD

**Issue by fatkodima** [gregnavis/active_record_doctor#65]
```ruby
class User
  has_one :account
end

class Account
  belongs_to :user
end
```

`has_one` should be backed by a unique index (on `accounts.user_id`), because otherwise user can have multiple accounts in the database.

There is already a check `MissingUniqueIndexes`, checking unique validations without indexes. It is pretty generically named and seems like this new check would be added into there? Or a new check created?

@gregnavis, wdyt?

**Comment by fatkodima** [comment]
@gregnavis Is this a good idea?

**Comment by gregnavis** [comment]
@fatkodima, I think it's a great idea! `MissingUniqueIndexes` seems to be the right place for that check.
