### ISSUE TITLE
False positive for extraneous Postgres trigram index

### ISSUE THREAD

**Issue by amckinnell** [gregnavis/active_record_doctor#69]
Here is a fragment from my `schema.rb` file that is flagged by `rails active_record_doctor:extraneous_indexes` as having an extraneous index that I believe is a false positive.

```ruby
t.index ["code", "account_id"], name: "index_skus_on_code_and_account_id", unique: true
t.index ["code"], name: "index_skus_on_code_trgm", opclass: :gin_trgm_ops, using: :gin
```
The output from running `rails active_record_doctor:extraneous_indexes` is:

```text
The following indexes are extraneous and can be removed:
  index_skus_on_code_trgm (can be handled by index_skus_on_code_and_account_id)
```

Thanks for making such a useful tool.

**Comment by gregnavis** [comment]
@amckinnell, thank you for reporting the issue. It'll be addressed in the upcoming release.
