### ISSUE TITLE
Default belongs_to validations don't trigger missing non-null constraint

### ISSUE THREAD

**Issue by jaredmoody** [gregnavis/active_record_doctor#72]
When belongs_to relationships are required by default, as they are in Rails 5.0+ config defaults, i.e.

`Rails.application.config.active_record.belongs_to_required_by_default = true`

Then `belongs_to` relationships without `optional: true` have a validation attached that is not detected by `MissingNonNullConstraint` when that same column does not have a `null: false` constraint in the database.

I think these should be detected and reported?

**Comment by fatkodima** [comment]
Seems like this is already reported?

For simple models:
```ruby
class User < ApplicationRecord
end

class Project < ApplicationRecord
  belongs_to :user
end
```

I got:
```
$ add `NOT NULL` to projects.user_id - Project validates its presence but it's not non-NULL in the database
```

**Comment by jaredmoody** [comment]
Maybe I missed something…

I’ll see if I can put together a repo to demonstrate or prove myself wrong 🙃

**Comment by gregnavis** [comment]
@jaredmoody, were you able to reproduce the error?

**Comment by jaredmoody** [comment]
Built a sample repo/rails app and it seems to be working correctly there, so closing.
