### ISSUE TITLE
False Positive: missing_non_null_constraint using STI

### ISSUE THREAD

**Issue by jaredmoody** [gregnavis/active_record_doctor#73]
Example:
 
```
class Word < ActiveRecord::Base
end

class Adjective < Word
  belongs_to :object
end
```

missing_non_null_constraint reports a missing null constraint on Adjective#object when it should not.

**Comment by gregnavis** [comment]
@jaredmoody, thank you for opening the issue and helping make `active_record_doctor` better.

I think that when STI is in use then we should generate a warning if and only if **all** models expect a given attribute to be present. If at least one model allows an empty value then no error should be reported.

Your issue highlights a problem with how `missing_non_null_constraint` is implemented. Currently, it iterates over **models** but problems it reports pertain to **tables**. One idea is to make it iterate over tables and determine which columns should have a non-NULL constraint based on **all** models backed by that table.
