### ISSUE TITLE
Feature Request: Ignore checks

### ISSUE THREAD

**Issue by jaredmoody** [gregnavis/active_record_doctor#74]
I'd like to run active_record_doctor as part of my CI, but need a way to ignore violations and/or false positives.

**Comment by gregnavis** [comment]
Thank you for opening the issue, @jaredmoody. It's already on `master` but I need to prepare a release, including documentation. For now, you can install from `master` and then add a config file named `.active_record_doctor` to your project root. You can use [`default.rb` from the repo](https://github.com/gregnavis/active_record_doctor/blob/91b2f6311a3ace35489d43edb8485a3ccbb6d5c0/lib/active_record_doctor/config/default.rb) for reference.

If you stumble upon any bugs then feel free to open issues here.

**Comment by gregnavis** [comment]
@jaredmoody, I've just released 1.9.0.rc1. Please give it a shot:

```ruby
gem "active_record_doctor", "= 1.9.0.rc1"
```

and run `bundle install`. Detailed installation and usage instructions are in the README. If you stumble upon any issues then please report them here.

**Comment by gregnavis** [comment]
I'm closing the issue as it's addressed in 1.9.0 which I released a few minutes ago.
