### ISSUE TITLE
Check for missing length validations

### ISSUE THREAD

**Issue by fatkodima** [gregnavis/active_record_doctor#92]
It will be a good idea to require field length validations (`validates :name, length: { maximum: 64 }`) when a model has a field limit in the database (`t.string :name, limit: 64`).

This way we will not make a useless save and rollback to the database for invalid fields, but also have properly populated validation errors.

**Comment by gregnavis** [comment]
Great idea, @fatkodima! If you don't mind, I'd like to take a stab at implementing it.

**Comment by fatkodima** [comment]
Yes, sure 👍

**Comment by gregnavis** [comment]
Implemented in bd65bda252e5773ddac0ba7c5df14f3b3f3dfef9. Thanks for the suggestion!
